
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '\n&\xde{>Q\x9a\xcc:\x02\xd4\xc7\xd1|\xff^'
    
_lr_action_items = {'PREFIX':([0,],[2,]),'POINT':([3,],[4,]),'URI':([2,],[3,]),'$end':([1,4,],[0,-1,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'prefix_uri':([0,],[1,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> prefix_uri","S'",1,None,None,None),
  ('prefix_uri -> PREFIX URI POINT','prefix_uri',3,'p_prefix_uri','D:\\Studys\\Master Thesis\\MagicCream\\Engine\\Decomposer\\parseMetadata.py',30),
  ('prefix_uri_list -> prefix_uri_list prefix_uri','prefix_uri_list',2,'p_prefix_uri_list','D:\\Studys\\Master Thesis\\MagicCream\\Engine\\Decomposer\\parseMetadata.py',36),
  ('prefix_uri_list -> prefix_uri','prefix_uri_list',1,'p_single_prefix_uri_list','D:\\Studys\\Master Thesis\\MagicCream\\Engine\\Decomposer\\parseMetadata.py',42),
]
